package Greencycle.dao;

import Greencycle.model.AddressBean;
import Greencycle.db.DBConnection;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

public class AddressDao {

    // Get all addresses for a customer
    public List<AddressBean> getAddressesByCustomerID(String customerID) {
        List<AddressBean> addresses = new ArrayList<>();
        String sql = "SELECT * FROM Address WHERE customerID = ? ORDER BY createdAt DESC";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, customerID);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                AddressBean addr = new AddressBean();
                addr.setAddressID(rs.getInt("addressID")); // Now directly int
                addr.setCategoryOfAddress(rs.getString("categoryOfAddress"));
                addr.setAddressLine1(rs.getString("addressLine1"));
                addr.setAddressLine2(rs.getString("addressLine2"));
                addr.setPoscode(rs.getString("poscode"));
                addr.setCity(rs.getString("city"));
                addr.setState(rs.getString("state"));
                addr.setRemarks(rs.getString("remarks"));
                addr.setCreatedAt(rs.getTimestamp("createdAt"));
                addr.setCustomerID(rs.getString("customerID"));
                addresses.add(addr);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return addresses;
    }

    // Save new address — addressID is auto-generated by DB
    public boolean saveAddress(AddressBean address) {
        String sql = "INSERT INTO Address (categoryOfAddress, addressLine1, addressLine2, poscode, city, state, remarks, customerID) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setString(1, address.getCategoryOfAddress());
            ps.setString(2, address.getAddressLine1());
            ps.setString(3, address.getAddressLine2());
            ps.setString(4, address.getPoscode());
            ps.setString(5, address.getCity());
            ps.setString(6, address.getState());
            ps.setString(7, address.getRemarks());
            ps.setString(8, address.getCustomerID());

            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                // Optional: retrieve and set the generated ID back into the bean
                try (ResultSet generatedKeys = ps.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        address.setAddressID(generatedKeys.getInt(1));
                    }
                }
                return true;
            }
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
        return false;
    }

    // Update address
    public boolean updateAddress(AddressBean address) {
        String sql = "UPDATE Address SET categoryOfAddress = ?, addressLine1 = ?, addressLine2 = ?, "
                   + "poscode = ?, city = ?, state = ?, remarks = ? WHERE addressID = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, address.getCategoryOfAddress());
            ps.setString(2, address.getAddressLine1());
            ps.setString(3, address.getAddressLine2());
            ps.setString(4, address.getPoscode());
            ps.setString(5, address.getCity());
            ps.setString(6, address.getState());
            ps.setString(7, address.getRemarks());
            ps.setInt(8, address.getAddressID()); // Now int

            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }

    // Delete address
    public boolean deleteAddress(int addressID) { // Changed parameter to int
        String sql = "DELETE FROM Address WHERE addressID = ?";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setInt(1, addressID);
            return ps.executeUpdate() > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    }
    
    // In AddressDao
public AddressBean getAddressByID(String addressID) {
    String sql = "SELECT * FROM Address WHERE addressID = ?";
    try (Connection conn = DBConnection.getConnection();
         PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setString(1, addressID);
        ResultSet rs = ps.executeQuery();
        if (rs.next()) {
            AddressBean addr = new AddressBean();
            addr.setAddressID(rs.getInt("addressID"));
            addr.setCategoryOfAddress(rs.getString("categoryOfAddress"));
            addr.setAddressLine1(rs.getString("addressLine1"));
            addr.setAddressLine2(rs.getString("addressLine2"));
            addr.setPoscode(rs.getString("poscode"));
            addr.setCity(rs.getString("city"));
            addr.setState(rs.getString("state"));
            addr.setRemarks(rs.getString("remarks"));
            addr.setCreatedAt(rs.getTimestamp("createdAt"));
            addr.setCustomerID(rs.getString("customerID"));
            return addr;
        }
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return null;
}

}